hello/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path("",views.index, name="index"),
    path("brian",views.brian, name="brian"),
    path("david",views.david, name="david"),
    path("<str:name>", views.greet, name="greet")
]

newyear/urls.py
from django.urls import path
from . import views
app_name="newyear"
urlpatterns = [
    path("",views.index, name="index")
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include('hello.urls')),
    path('newyear/', include('newyear.urls')),
    path('tasks/', include('tasks.urls'))
]

tasks/urls.py
from unicodedata import name
from django.urls import path
from . import views
app_name="task"
urlpatterns = [
    path("",views.index,name="index"),
    path("add/",views.add,name="add")
]

hello/models.py
from django.db import models

# Create your models here.

newyear/models.py
from django.db import models

# Create your models here.

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
def index(request):
    return render(request,"hello/index.html")

def brian(request):
    return HttpResponse("hello brian")

def david(request):
    return HttpResponse("hello david")
def greet(request,name):
    return render(request, "hello/greet.html",{"name":name.capitalize()})

newyear/views.py
from django.shortcuts import render
import datetime
# Create your views here.
def index(request):
    now=datetime.datetime.now()
    return render(request, "newyear/index.html",{
        "newyear": now.month==1 and now.day==1
    })

tasks/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
class NewTaskForm(forms.Form):
    input_task= forms.CharField(label="New Task")
    priority=forms.IntegerField(label="Priority",min_value=1,max_value=5)

list_task=[]
def index(request):
    if "task" not in request.session:
        request.session["task"]=[]
    return render(request, "tasks/index.html",{"task":request.session["task"]})

def add(request):
    if request.method=="POST":
        form=NewTaskForm(request.POST)
        if form.is_valid():
            get_task=form.cleaned_data["input_task"]
            request.session["task"]+=[get_task]
            return HttpResponseRedirect(reverse("task:index"))
        else:
            return render(request,"tasks/add.html",{"form":form})
        
    return render(request,"tasks/add.html",{"form":NewTaskForm()})

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>  
    <body>
        <h1> hello {{name}}</h1>
    </body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Hello</title>
    </head>  
    <body>
        <h1> hello world</h1>
    </body>
</html>

newyear/templates/newyear/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Is it newyear??</title>
        <link href="{%static 'newyear/style.css'%}" rel="stylesheet">

    </head>  
    <body>
        {% if newyear%}
            <h1> YES</h1>
        {% else %}
            <h1> NO </h1>
        {%endif%}
    </body>
</html>

tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}
    {%block body%}
            <h1>Add Task</h1>
        <form action="{% url 'task:add'%}" method="post">
            {% csrf_token %}
            {{form}}
            <button type="submit">submit</button>
        </form>
        <a href="{% url 'task:index' %}">Go Back To Tasks</a>
    {%endblock%}

tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}
    {% block body %}
        <h1>Tasks</h1>
            <ul>
                {%for i in task%}
                    <li>{{i}}</li>
                    {%empty%}
                        no task
                {% endfor %}
            </ul>
            <a href="{%url 'task:add'%}">Add a new task</a>
    {% endblock  %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tasks</title>
    </head>
    <body>
       {% block body %}
       {% endblock  %}
    </body
</html>